export default {
    LOGIN: 'Login',
    SIGNUP: 'signup',
    HOME: 'Home',
    FORGOT_PASSWORD: 'ForgotPassword',
    DRAWER: 'Drawer',
    TAB: 'Tab',
    SETTINGS: 'Settings',
    OTP_LOGIN: "OtpLogin",
    CONFIRM_OTP: 'ConfirmOtp',
    ADMIN_HOME: 'AdminHome',
    UPLOAD_NEW_PRODUCT: 'UploadNewProduct',
    UPLOAD_CATEGORY: 'UploadCategory',
    CATEGORY_BASED_PRODUCTS: 'CateoryBasedProducts',
    UPLOAD_OFFERS: 'UploadOffer',
    VIEW_PRODUCT: 'ViewProduct',
    CART: 'Cart',
}