export default {
    LOGIN: 'Login',
    SIGNUP: 'signup',
    HOME: 'home',
    FORGOT_PASSWORD: 'ForgotPassword',
    DRAWER: 'Drawer',
    SETTINGS: 'Settings',
    OTP_LOGIN: "OtpLogin",
    CONFIRM_OTP:'ConfirmOtp',
    ADMIN_HOME: 'AdminHome',
    UPLOAD_NEW_PRODUCT: 'UploadNewProduct',
    UPLOAD_CATEGORY: 'UploadCategory',
    CATEGORY_BASED_PRODUCTS: 'CateoryBasedProducts',
    UPLOAD_OFFERS:'UploadOffer',
    VIEW_PRODUCT:'ViewProduct',
}